resource_synchronizer_msgs/MetaStateMachineHeader header
SubStateMachine_pepper_head_manager_msgs state_machine_pepper_head_manager
SubStateMachine_pepper_arm_manager_msgs state_machine_pepper_arm_manager_left
SubStateMachine_pepper_arm_manager_msgs state_machine_pepper_arm_manager_right
SubStateMachine_pepper_base_manager_msgs state_machine_pepper_base_manager
---
int32 id
string error